### ISSUE TITLE
how to plot 3dbb without P2

### ISSUE THREAD

**Issue by yasserius** [lzccccc/3d-bounding-box-estimation-for-autonomous-driving#10]
Hi, 

firstly, excellent repo, very nicely written code, love it!

But I am confused a bit with the math.

The model outputs 2 orientation values, a sin and a cosine of the local orientation alpha, as predictions.

But while looking at `visualization3Dbox.py`, it appears that it used the `P2` provided by the calib data.

So how will plotting happen for an unseen image, when `P2` for it isn't available?

Let me know if I failed to explain myself. Thanks!

**Comment by lzccccc** [comment]
Hi,

It is not possible if you don't know `P2`.
This is called the camera intrinsic matrix which transforms the camera coordinate to pixel coordinate.

**Comment by yasserius** [comment]
That's a bummer.

So it means if I have some random footage of the road, then this model doesn't work?

If so, are there any other models that you know that are independent of `P2`?
