### ISSUE TITLE
some problem about  KITTI data set

### ISSUE THREAD

**Issue by fsxy1063200037** [lzccccc/3d-bounding-box-estimation-for-autonomous-driving#9]
I have problem with preparing KITTI data set. I download the data set you mention and the box_3d, label_02 and calib_02 file is missing can you please give me the proper link with these folders.
Thank you

**Comment by lzccccc** [comment]
box_3d is the predicted results.
label_02: http://www.cvlibs.net/download.php?file=data_object_label_2.zip
calib_02: http://www.cvlibs.net/download.php?file=data_object_calib.zip

**Comment by fsxy1063200037** [comment]
Thank you very much------------------ 原始邮件 ------------------
发件人: "lzccccc"<notifications@github.com>
发送时间: 2020年4月11日(星期六) 上午8:58
收件人: "lzccccc/3d-bounding-box-estimation-for-autonomous-driving"<3d-bounding-box-estimation-for-autonomous-driving@noreply.github.com>;
抄送: "fsxy1063200037"<1063200037@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lzccccc/3d-bounding-box-estimation-for-autonomous-driving] someproblem about  KITTI data set (#9)




 
box_3d is the predicted results.
 label_02: http://www.cvlibs.net/download.php?file=data_object_label_2.zip
 calib_02: http://www.cvlibs.net/download.php?file=data_object_calib.zip
 
&mdash;

**Comment by fsxy1063200037** [comment]
I'm sorry I was misrepresented.
I need the label_02 and calib_02 datasets in this  2011_09_26_drive_0084_sync folder, not the label_2 and calib in training folder
├── 2011_09_26
│   └── 2011_09_26_drive_0084_sync
│           ├── box_3d       <- predicted data
│           ├── **calib_02**
│           ├── calib_cam_to_cam.txt
│           ├── calib_velo_to_cam.txt
│           ├── image_02
│           ├── **label_02**
│           └── tracklet_labels.xml
can you please give me the proper link with these folders.
Thank you

**Comment by lzccccc** [comment]
The label and calib files are transformed from KITTI raw data.
I recommend you to first browse the KITTI website and project folder.
The parse_raw_to_KITTI_form.py file is used to preprocess raw data.

**Comment by fsxy1063200037** [comment]
Thank you, I try it
